name: AutoCalendar

on:
  workflow_dispatch:
  schedule:
    - cron: "5 0 * * *"

permissions:
  actions: write  
  contents: write  

jobs:
  ForkRepository:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"

    steps:
    # 检出目标存储库
    - name: 验证目标存储库
      uses: actions/checkout@v4.2.2
      with:
        repository: Moli-X/Calendar
        path: Calendar-repo
        token: ${{ secrets.GitHub_TOKEN }}  

    # 下载中国假期 .ics 文件
    - name: 下载中国假期 .ics 文件
      run: |
        mkdir -p Calendar-repo/Holiday
        curl -L --output Calendar-repo/Holiday/ChinaHolidays.ics https://calendars.icloud.com/holidays/cn_zh.ics

    # 确保文件编码为 UTF-8
    - name: 确保文件编码为 UTF-8
      run: |
        # 如果需要转换编码，可以使用 iconv
        for file in Calendar-repo/Holiday/ChinaHolidays.ics; do
          iconv -f GB18030 -t UTF-8//IGNORE "$file" -o "$file" || echo "Error processing $file"
        done

    # 添加Commits
    - name: 添加Commits
      run: |
        cd Calendar-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    # 清理Workflow
    - name: 清理Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GitHub_TOKEN }} 
        retain_days: 0
        keep_minimum_runs: 2
