# 更新日期：2025-01-02
name: AutoCalendar

on:
  workflow_dispatch:
  schedule:
    - cron: "5 0 * * *"

permissions:
  actions: write  
  contents: write  

jobs:
  ForkRepository:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"


    steps:
    - name: 验证目标存储库
      uses: actions/checkout@v4.2.2
      with:
        repository: Moli-X/Calendar
        path: Calendar-repo
        token: ${{ secrets.GitHub_TOKEN }}  
    

    - name: Download ChinaHolidays.ics
      run: |
        curl -L -o Calendar-repo/Holiday/ChinaHolidays.ics "https://calendars.icloud.com/holidays/cn_zh.ics"
        # 确保文件已经下载
        ls -l Calendar-repo/Holiday/

    - name: Check file type and attempt decompression
      run: |
        # 检查文件是否是gzip压缩文件
        file Calendar-repo/Holiday/ChinaHolidays.ics
        # 如果是gzip文件，解压它
        if file Calendar-repo/Holiday/ChinaHolidays.ics | grep -q "gzip compressed data"; then
          echo "Gzip file detected, decompressing..."
          mv Calendar-repo/Holiday/ChinaHolidays.ics Calendar-repo/Holiday/ChinaHolidays.ics.gz
          gzip -d Calendar-repo/Holiday/ChinaHolidays.ics.gz
          # 确保解压后文件存在
          ls -l Calendar-repo/Holiday/
        else
          echo "Not a gzip file, skipping decompression."
        fi

    - name: Convert ChinaHolidays.ics encoding to UTF-8
      run: |
        # 确保文件存在并检查编码
        file Calendar-repo/Holiday/ChinaHolidays
        # 转换编码为 UTF-8
        iconv -f WINDOWS-1252 -t UTF-8 Calendar-repo/Holiday/ChinaHolidays -o Calendar-repo/Holiday/ChinaHolidays_utf8.ics
        # 删除错误字符
        iconv -c -f utf-8 -t utf-8 Calendar-repo/Holiday/ChinaHolidays -o Calendar-repo/Holiday/ChinaHolidays_utf8_no_errors.ics
        # 清理文件
        iconv -c -f utf-8 -t utf-8 Calendar-repo/Holiday/ChinaHolidays -o Calendar-repo/Holiday/ChinaHolidays_cleaned.ics









    # 复刻黄历原始文件
    - name: 复刻黄历原始文件
      run: |
        mkdir -p Calendar-repo/Almanac
        curl -L -o Calendar-repo/Almanac/Almanac.ics "https://raw.githubusercontent.com/zqzess/holiday-and-chinese-almanac-calendar/main/holidays_calendar.ics"


    # 添加Commits
    - name: 添加Commits
      run: |
        cd Calendar-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    # 清理Workflow
    - name: 清理Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GitHub_TOKEN }} 
        retain_days: 0
        keep_minimum_runs: 2
