# 更新日期：2025-01-02
name: AutoCalendar

on:
  workflow_dispatch:
  schedule:
    - cron: "5 0 * * *"

permissions:
  actions: write  
  contents: write  

jobs:
  ForkRepository:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"


    steps:
    - name: 验证目标存储库
      uses: actions/checkout@v4.2.2
      with:
        repository: Moli-X/Calendar
        path: Calendar-repo
        token: ${{ secrets.GitHub_TOKEN }}  
    

    # 复刻假期原始文件
    - name: 复刻假期原始文件
      run: |
        mkdir -p Calendar-repo/Holiday
        curl -o Calendar-repo/Holiday/ChinaHolidays.ics https://calendars.icloud.com/holidays/cn_zh.ics



    # 复刻黄历原始文件
    - name: 复刻黄历原始文件
      run: |
        mkdir -p Calendar-repo/Almanac
        curl -L -o Calendar-repo/Almanac/Almanac.ics "https://raw.githubusercontent.com/zqzess/holiday-and-chinese-almanac-calendar/main/holidays_calendar.ics"

    # 处理并确保UTF-8编码
    - name: 确保文件编码为UTF-8
      run: |
        # 确保中国假期和黄历文件编码为 UTF-8
        for file in Calendar-repo/Holiday/ChinaHolidays.ics; do
          iconv -f GB18030 -t UTF-8 "$file" -o "$file"
        done



    # 添加Commits
    - name: 添加Commits
      run: |
        cd Calendar-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    # 清理Workflow
    - name: 清理Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GitHub_TOKEN }} 
        retain_days: 0
        keep_minimum_runs: 2
