# 更新日期：2025-01-02
name: AutoCalendar

on:
  workflow_dispatch:
  schedule:
    - cron: "5 0 * * *"

permissions:
  actions: write  
  contents: write  

jobs:
  ForkRepository:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"


    steps:
    - name: 验证目标存储库
      uses: actions/checkout@v4.2.2
      with:
        repository: Moli-X/Calendar
        path: Calendar-repo
        token: ${{ secrets.GitHub_TOKEN }}  
    

    # 复刻假期原始文件
    - name: 复刻假期原始文件
      run: |
        mkdir -p Calendar-repo/Holiday
        curl -L --retry 3 --max-time 60 -o Calendar-repo/Holiday/ChinaHolidays.ics "https://calendars.icloud.com/holidays/cn_zh.ics"

    # 重命名文件并解压
    - name: Rename and Unzip ChinaHolidays.ics
      run: |
        mv Calendar-repo/Holiday/ChinaHolidays.ics Calendar-repo/Holiday/ChinaHolidays.ics.gz
        gzip -d Calendar-repo/Holiday/ChinaHolidays.ics.gz

    # Check and convert encoding to UTF-8
    - name: Convert ChinaHolidays.ics encoding to UTF-8
      run: |
        # Check the file encoding
        file Calendar-repo/Holiday/ChinaHolidays
        # Convert from WINDOWS-1252 or GB2312 to UTF-8
        iconv -f WINDOWS-1252 -t UTF-8 Calendar-repo/Holiday/ChinaHolidays -o Calendar-repo/Holiday/ChinaHolidays_utf8.ics
        # Remove invalid characters if any
        iconv -c -f utf-8 -t utf-8 Calendar-repo/Holiday/ChinaHolidays -o Calendar-repo/Holiday/ChinaHolidays_utf8_no_errors.ics
        # Clean the file to remove BOM or invalid characters
        iconv -c -f utf-8 -t utf-8 Calendar-repo/Holiday/ChinaHolidays -o Calendar-repo/Holiday/ChinaHolidays_cleaned.ics










    # 复刻黄历原始文件
    - name: 复刻黄历原始文件
      run: |
        mkdir -p Calendar-repo/Almanac
        curl -L -o Calendar-repo/Almanac/Almanac.ics "https://raw.githubusercontent.com/zqzess/holiday-and-chinese-almanac-calendar/main/holidays_calendar.ics"


    # 添加Commits
    - name: 添加Commits
      run: |
        cd Calendar-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    # 清理Workflow
    - name: 清理Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GitHub_TOKEN }} 
        retain_days: 0
        keep_minimum_runs: 2
