name: AutoCalendar

on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"

permissions:
  actions: write  
  contents: write  

jobs:
  ForkRepository:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps:
    - name: 验证目标存储库
      uses: actions/checkout@v4.2.2
      with:
        repository: Moli-X/Calendar
        path: Calendar-repo
        token: ${{ secrets.GitHub_TOKEN }}  
    
    # 复刻天气原始文件
    - name: 复刻天气原始文件
      run: |
        mkdir -p Calendar-repo/.github/Record
        curl -L -o Calendar-repo/.github/Record/ChinaHolidays.ics "https://calendars.icloud.com/holidays/cn_zh.ics"
        curl -L -o Calendar-repo/.github/Record/HolidayCal.ics "https://raw.githubusercontent.com/lanceliao/china-holiday-calender/master/holidayCal.ics"

    # 复刻天气原始文件
    - name: 复刻天气原始文件
      run: |
        mkdir -p Calendar-repo/Weather/Record
          "Aomen" "Anshun" "Anquan" "Anzhou"
          "BeiJing" "BaoDing" "BaoTou" "BengBu" "BingZhou" "BoZhou"
          "ChongQing" "ChangChun" "ChangSha" "ChengDu" "ChuZhou"
          "DaLian" "DongGuan" "DanDong" "DeZhou" "DongYing"
          "FuZhou" "FoShan" "FuYang" "FuJian" "FuShun"
          "GuangZhou" "GuiZhou" "GuiLin" "GanSu" "GuangXi"
          "HangZhou" "HeFei" "HeBei" "HaiNan" "HuNan"
          "JiNan" "JiuJiang" "JiangXi" "JiangSu" "JiLin"
          "KunMing" "KaiYuan" "KaiLi"
          "LianYunGang" "LiJiang" "LongYan" "LiangPing" "LuZhou"
          "MeiZhou" "MianYang" "Macau"
          "NanJing" "NanChang" "NanNing" "NanYang" "NingBo"
          "PingDingShan" "PingXiang" "PuTian" "PingYang"
          "QingDao" "QingHai" "QianNan" "QinZhou"
          "ShenZhen" "ShangHai" "SuZhou" "ShiJiaZhuang" "ShaoXing"
          "TianJin" "TaiYuan" "TaiZhou" "TongHua" "TaiAn"
          "WuHan" "WenZhou" "WeiFang" "WuLuMuQi" "WuXi"
          "XiAn" "XiaMen" "XingTai" "XiangYang" "XuZhou"
          "YanTai" "YiChang" "YuNan" "YuXi" "YiBin"
          "ZhuHai" "ZhengZhou" "ZunYi" "ZhongShan" "ZiBo" "ZhouKou"
        )
        
        # 下载每个城市的天气数据
        for city in "${cities[@]}"; do
          curl -L -o "Calendar-repo/Weather/Record/${city}.ics" "https://weather-in-calendar.com/cal/weather-cal.php?city=${city}&units=metric&temperature=day"
        done

    # 修改并移动所有天气文件
    - name: 修改并移动所有天气文件
      run: |
        mkdir -p Calendar-repo/Weather
        
        declare -A wind_directions=(
        ["N"]="北"
        ["S"]="南"
        ["E"]="东"
        ["W"]="西"
        ["NE"]="东北"
        ["NW"]="西北"
        ["SE"]="东南"
        ["SW"]="西南"
        ["NNW"]="北西北"
        ["NNE"]="北东北"
        ["SSW"]="南西南"
        ["SSE"]="南东南"
        )
        
        # 遍历 Record 文件夹中的所有 .ics 文件
        for file_path in Calendar-repo/Weather/Record/*.ics; do
          file_name=$(basename "$file_path")  # 提取文件名
          city_name="${file_name%.ics}"  # 去掉后缀作为城市名

          mkdir -p "Calendar-repo/Weather/$city_name"  # 创建城市对应的文件夹

          # 遍历所有风向和箭头组合，动态生成替换规则
          for key in "${!wind_directions[@]}"; do
            sed -i \
              -e "s/from $key →/来自${wind_directions[$key]} →/g" \
              -e "s/from $key ←/来自${wind_directions[$key]} ←/g" \
              -e "s/from $key ↑/来自${wind_directions[$key]} ↑/g" \
              -e "s/from $key ↓/来自${wind_directions[$key]} ↓/g" \
              -e "s/from $key ↘/来自${wind_directions[$key]} ↘/g" \
              -e "s/from $key ↙/来自${wind_directions[$key]} ↙/g" \
              -e "s/from $key ↖/来自${wind_directions[$key]} ↖/g" \
              -e "s/from $key ↗/来自${wind_directions[$key]} ↗/g" \
              "$file_path"
          done

          # 针对其他天气描述的替换规则
          sed -i \
            -e 's/Overcast clouds/多云/g' \
            -e 's/Sky is clear/天气晴朗/g' \
            -e 's/Scattered clouds/局部多云/g' \
            -e 's/Broken clouds/部分多云/g' \
            -e 's/Few clouds/少量云/g' \
            -e 's/Light rain/小雨/g' \
            -e 's/Moderate rain/中雨/g' \
            -e 's/Heavy rain/大雨/g' \
            -e 's/Thunderstorm/雷暴/g' \
            -e 's/Snow/下雪/g' \
            -e 's/Light snow/小雪/g' \
            -e 's/Sunrise/日出/g' \
            -e 's/and sets/日落/g' \
            -e 's/Humidity/湿度/g' \
            -e 's/Wind speed up to/风速/g' \
            -e 's/Pressure/气压/g' \
            "$file_path"

          # 将修改后的文件移动到目标目录
          mv "$file_path" "Calendar-repo/Weather/$city_name/$file_name"
        done

    # 添加Commits
    - name: 添加Commits
      run: |
        cd Calendar-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    # 清理Workflow
    - name: 清理Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GitHub_TOKEN }} 
        retain_days: 0
        keep_minimum_runs: 2
