name: Generate China Holiday ICS

on:
  workflow_dispatch:
  schedule:
    - cron: "5 0 * * *"

permissions:
  actions: write
  contents: write  

jobs:
  generate-ics:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: 验证目标存储库
      uses: actions/checkout@v4.2.2
      with:
        repository: Moli-X/Calendar
        path: Calendar-repo
        token: ${{ secrets.GitHub_TOKEN }}  

    - name: List repository contents
      run: ls -l Calendar/Config  # 确保 Config 文件夹在指定路径下

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Calendar/Config/Requirements.txt  # 更新路径

    - name: Generate China Holiday ICS
      run: |
        python Calendar/Config/GenerateHoliday.py  # 更新路径

    - name: Upload ICS file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: china-holidays-ics
        path: Calendar/Config/china_holidays_*.ics  # 更新路径

    # 添加Commits
    - name: 添加Commits
      run: |
        cd Calendar-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    # 清理Workflow
    - name: 清理Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GitHub_TOKEN }} 
        retain_days: 0
        keep_minimum_runs: 2
