name: Generate China Holiday ICS

on:
  workflow_dispatch:
  schedule:
    - cron: "5 0 * * *"

permissions:
  actions: write
  contents: write  

jobs:
  generate-ics:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: 验证目标存储库
      uses: actions/checkout@v4.2.2
      with:
        repository: Moli-X/Calendar
        path: Calendar-repo  # 将仓库内容放到 Calendar-repo 文件夹下
        token: ${{ secrets.GitHub_TOKEN }}  

    - name: List Calendar-repo contents
      run: ls -l Calendar-repo  # 列出整个仓库的文件，确认路径和文件是否正确

    - name: List Config folder contents
      run: |
        ls -l Calendar-repo/Config  # 列出 Config 文件夹下的内容，确认文件是否存在

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cat Calendar-repo/Config/Requirements.txt  # 查看 Requirements.txt 文件内容，确认文件是否能正确读取
        pip install -r Calendar-repo/Config/Requirements.txt  # 使用正确路径

    - name: Generate China Holiday ICS
      run: |
        python Calendar-repo/Config/GenerateHoliday.py  # 使用正确路径

    - name: Upload ICS file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: china-holidays-ics
        path: Calendar-repo/Config/china_holidays_*.ics  # 使用正确路径

    # 添加Commits
    - name: 添加Commits
      run: |
        cd Calendar-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    # 清理Workflow
    - name: 清理Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GitHub_TOKEN }} 
        retain_days: 0
        keep_minimum_runs: 2
